###
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456"
}

> {%
    // client.global.set("token", response.body.data.token);
    client.global.set("token", response.body.token);
%}

###
POST {{base_url}}/auth/register
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "name": "John Doe",
  "password": "123456"
}

###
GET {{base_url}}/users
Authorization: Bearer {{token}}
